### ISSUE TITLE
reference error: React is not defined

### ISSUE THREAD

**Issue by x0cipher** [serlina-community/egg-serlina#1]
Hi, 

I am getting the following error when running the egg-server. I have followed the exact steps mentioned in the readme.

### Error Stack
```bash
yarn run v1.9.4
$ egg-bin dev
2018-08-22 14:21:02,457 INFO 14452 [master] node version v10.0.0
2018-08-22 14:21:02,457 INFO 14452 [master] egg version 2.10.0
2018-08-22 14:21:06,442 INFO 14452 [master] agent_worker#1:11420 started (3985ms)
2018-08-22 14:21:20,772 WARN 17680 [egg:core:ready_timeout] 10 seconds later C:\Users\######\node_modules\egg-watcher\app.js:15:7 was still unable to finish.
 DONE  Compiled successfully in 4000ms14:21:24

 DONE  Compiled successfully in 4235ms14:21:24

2018-08-22 14:21:24,897 INFO 14452 [master] egg started on http://127.0.0.1:7001 (22440ms)
 DONE  Compiled successfully in 7470ms14:21:28

2018-08-22 14:21:38,791 ERROR 17680 [-/127.0.0.1/-/32ms GET /home] nodejs.ReferenceError: React is not defined
    at exports.default (webpack:///./page/home.js?:8:5)
    at processChild (C:\Users\######\node_modules\react-dom\cjs\react-dom-server.node.development.js:2138:14)
    at resolve (C:\Users\######\node_modules\react-dom\cjs\react-dom-server.node.development.js:2064:5)
    at ReactDOMServerRenderer.render (C:\Users\######\node_modules\react-dom\cjs\react-dom-server.node.development.js:2383:22)
    at ReactDOMServerRenderer.read (C:\Users\######\node_modules\react-dom\cjs\react-dom-server.node.development.js:2357:19)
    at Object.renderToString (C:\Users\######\node_modules\react-dom\cjs\react-dom-server.node.development.js:2729:25)
    at Serlina.<anonymous> (C:\Users\######\node_modules\serlina\dist\serlina.js:200:41)
    at Generator.next (<anonymous>)
    at C:\Users\######\node_modules\serlina\dist\serlina.js:7:71
    at new Promise (C:\Users\######\node_modules\core-js\modules\es6.promise.js:177:7)

pid: 123456
hostname: ######
```

### Relevant Files
```javascript
// config.default.js
'use strict';

module.exports = appInfo => {
  const config = exports = {};

  // use for cookie sign key, should change to your own and keep security
  config.keys = appInfo.name + '_xxxxxxxxxxxxxxx';

  // add your config here
  config.middleware = [];
  
  config.serlina = {
    map: {
      '/home': 'home'
    }
  };
  
  return config;
};
```

```javascript
// plugin.js
exports.serlina = {
    enable: true,
    package: 'egg-serlina',
};
```

```javascript
// package.json
"dependencies": {
    "egg": "^2.2.1",
    "egg-scripts": "^2.5.0",
    "egg-serlina": "^0.1.2",
    "react": "^16.4.2",
    "react-dom": "^16.4.2"
  }
```

### Folder Structure
```bash
- root-dir
  - app
  - client
    - page
       - home.js
```

### Content of home.js
```javascript
export default () => {
    return <div>Hello Serlina</div>
}
```

Could you let me know what i might be doing wrong ?

**Comment by djyde** [comment]
Your `home.js` should import React

```diff
+ import * as React from 'react'
export default () => {
    return <div>Hello Serlina</div>
}
```

Sorry for my late reply. I didn't receive the notification.

**Comment by x0cipher** [comment]
@djyde awesome, it's working now. thanks !! 👍
